#!/bin/bash

set -euETo pipefail
shopt -s inherit_errexit

cd "$(dirname "$0")/.."

set -x

# reset changes to submodules
git submodule foreach --recursive git reset --hard
git submodule foreach --recursive git clean -fdx
git submodule update --init --recursive

# commit this file if changed
git commit scripts/update -m 'chore: update script updated' || true

# determine no pending changes that will be lost
git update-index --refresh
git diff-index --quiet HEAD -- || \
  echo "ERROR: Commit or revert changes or they will be lost"

# remove untracked artifacts
git clean -fdx

# pull latest upstream changes to this branch
git fetch -j8 origin
git merge --ff --no-edit origin/"$(git rev-parse --abbrev-ref HEAD)"
git submodule update --init --recursive

# fetch the latest submodule changes locally
git fetch --recurse-submodules -j8

# update each submodule to HEAD of default branch
# shellcheck disable=SC2016
git submodule foreach 'git checkout $(git rev-parse --abbrev-ref HEAD);git submodule update --recursive'

(
  cd .vim/bundle/coc.nvim && npm install
)
