return {
	"williamboman/mason-lspconfig.nvim",
	opts = {
		automatic_installation = true,
		ensure_installed = {
			"beautysh",
			"bash-language-server bashls",
			"docker-compose-language-service docker_compose_language_service",
			"dockerfile-language-server dockerls",
			"eslint-lsp eslint",
			"hadolint",
			"json-lsp jsonls",
			"lua-language-server lua_ls",
			"luacheck",
			"luaformatter",
			"markdownlint",
			"marksman",
			"shellcheck",
			"shfmt",
			"stylua",
			"typescript-language-server tsserver",
			"vim-language-server vimls",
			"yaml-language-server yamlls",
		},
	},
}
