#!/usr/bin/env bash

update-bitwarden() (
  print-msg "=> bitwarden\n"
  if [[ ! -f $HOME/.local/bin/bitwarden ]]; then
    "==> installing\n"
    (
      set -x
      curl -fLo "$HOME/.local/bin/bitwarden" \
        --create-dirs \
        'https://func.bitwarden.com/api/dl/?app=desktop&platform=linux'
      chmod u+x "$HOME/.local/bin/bitwarden"
    )
  elif [[ "$(date -r "$HOME/.local/bin/bitwarden" +%s)" -ge "$(date -r "$HOME/.local/share/applications/bitwarden.desktop" +%s)" ]]; then
    print-msg "==> updating desktop shortcut\n"
    (
      set -x
      rm -f /tmp/fifo
      mkfifo /tmp/fifo
      exec 3<> /tmp/fifo
      bitwarden --appimage-mount >&3 &
      BITWARDEN_MOUNT_PID=$!
      trap 'kill "$BITWARDEN_MOUNT_PID"; exec 3>&-; rm /tmp/fifo' ERR
      read -r BITWARDEN_MOUNT_DIR <&3
      (set +x && print-msg "===> updating bitwarden.png\n")
      cp "$BITWARDEN_MOUNT_DIR/bitwarden.png" "$HOME/.local/share/icons"
      (set +x && print-msg "===> updating bitwarden.desktop\n")
      sed \
        -e "s@^Exec=.*@Exec=$HOME/.local/bin/bitwarden --no-sandbox %U@" \
        -e "s@^Icon=.*@Icon=$HOME/.local/share/icons/bitwarden.png@" \
        < "$BITWARDEN_MOUNT_DIR/bitwarden.desktop" \
        > "$HOME/.local/share/applications/bitwarden.desktop"
      (set +x && print-msg "===> cleaning up\n")
      kill "$BITWARDEN_MOUNT_PID"
      trap - ERR
      exec 3>&-
      rm /tmp/fifo
    )
  fi
)

update-bitwarden-cli() (
  print-msg "=> bw\n"
  if [[ ! -f $HOME/.local/bin/bitwarden ]]; then
    print-msg "==> installing\n"
    (
      set -x
      curl -fLo "$HOME/bw.zip" \
        'https://func.bitwarden.com/api/dl/?app=cli&platform=linux'
      unzip -o "$HOME/bw.zip"
      rm "$HOME/bw.zip"
      chmod u+x "$HOME/bw"
      mv "$HOME/bw" "$HOME/.local/bin"
    )
  elif [[ "$(date -r "$HOME/.local/bin/bw" +%s)" -le "$(date -d "yesterday" +%s)" ]]; then
    print-msg "==> updating\n"
    (set -x && bw update)
  fi
)

if [[ "${DOTFILES_SECURE:-false}" == true ]]; then
  update-bitwarden
  update-bitwarden-cli
fi
