#!/usr/bin/env bash

update-bitwarden-cli() (
  URI='https://func.bitwarden.com/api/dl/?app=cli&platform=linux'
  if [[ ! -f $HOME/.local/bin/bitwarden ]]; then
    print-info "==> installing\n"
  else
    URI=$(bw update | sed -nr 's@You can download this update at (https://.*zip)$@\1@p')
    if [[ -n "${URI}" ]]; then
      print-info "==> updating\n"
    fi
  fi

  # install binary
  if [[ -n "${URI}" ]]; then
    (
      set -x
      curl -fLo /tmp/bw.zip "$URI"
      unzip -o /tmp/bw.zip
      mv /tmp/bw "$HOME/.local/bin"
      chmod u+x "$HOME/.local/bin/bw"
      rm /tmp/bw.zip
    )
  fi
)

run-module true x86_64
