#!/usr/bin/env bash

declare -a ppas=(
    ppa:mooltipass/moolticute
)

declare -a packages=(
    antiword # for recoll
    aspell   # for recoll
    bindfs
    colorized-logs # for ansi2txt to remove stupid color when deep searching logs
    gajim
    gajim-omemo
    gawk
    libimage-exiftool-perl # for recoll
    poppler-utils          # for recoll
    python3.11-venv
    recollcmd
    shellcheck
    sxiv # image viewer
    wl-clipboard
    build-essential
    libreadline-dev
    wv # for recoll
)

(
    UBUNTU_CODENAME="$(grep -oE "UBUNTU_CODENAME=\S+" </etc/os-release | cut -d'=' -f2)"
    for ppa in "${ppas[@]}"; do
        if ! add-apt-repository -L | grep -qe "${ppa#ppa:}.*$UBUNTU_CODENAME"; then
            (set -x && sudo add-apt-repository -y "$ppa")
        fi
    done
    for package in "${packages[@]}"; do
        if ! dpkg-query -W -f='${Status}' "$package" | sed -r "s/.*(installed).*/\1: $package\n/"; then
            (set -x && sudo apt-get update && sudo apt-get install -y "${packages[@]}")
            break
        fi
    done
)

PATH=".local/bin:$PATH"

set -x

## gnome-terminal

# install font
if [ ! -f ~/.local/share/fonts/'DejaVu Sans Mono for Powerline.ttf' ]; then
    curl -fLo ~/.local/share/fonts/'DejaVu Sans Mono for Powerline.ttf' --create-dirs https://github.com/powerline/fonts/raw/master/DejaVuSansMono/DejaVu%20Sans%20Mono%20for%20Powerline.ttf
    fc-cache -f -v
fi
# TODO https://github.com/prettier/vim-prettier for bash?
