#!/usr/bin/env bash
curl -L \
  -H "Accept: application/vnd.github+json" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/repos/mullvad/mullvadvpn-app/releases |
  echo '[{"draft": false, "a":"b"}, {"draft": false, "a":"b"}]' | jq '.[] | first(select(.draft == false)) | .tag_name'

  jq '.[] | first(select((.tag_name | test("^\\d{4}\\.\\d+"; "x")?) and .prerelease == false and .draft == false)) | .tag_name'

  jq '.[] | select((.tag_name | test("^\\d{4}\\.\\d+"; "x")?) and .prerelease == false and .draft == false) | .tag_name'

  jq '.[] | select(.prerelease == false and .draft == false and .tag_name | test("^\\d{4}")?)'

update-bitwarden-cli() (
  URI='https://func.bitwarden.com/api/dl/?app=cli&platform=linux'
  if [[ ! -f $HOME/.local/bin/bitwarden ]]; then
    print-info "==> installing\n"
  else
    URI=$(bw update | sed -nr 's@You can download this update at (https://.*zip)$@\1@p')
    if [[ -n "${URI}" ]]; then
      print-info "==> upgrading\n"
    fi
  fi

  # install binary
  if [[ -n "${URI}" ]]; then
    (
      set -x
      curl -fLo /tmp/bw.zip "$URI"
      (
        cd "$HOME/.local/bin" || exit 1
        unzip -o /tmp/bw.zip
        chmod u+x bw
      )
      rm /tmp/bw.zip
    )
  fi
)

run-module true x86_64
