#!/usr/bin/env bash

update-zsh() (
  print-msg "=> zsh\n"

  # submodule update script should take care of this
  # # updating zsh
  # print-msg "==> updating oh-my-zsh\n"
  # "$HOME/.oh-my-zsh/tools/upgrade.sh"

  # set shell
  if [[ "$(basename -- "$SHELL")" != "zsh" ]]; then
    print-msg "==> updating user shell\n"
    chsh -s "$(command -v zsh)" "$USER"
  fi

  # install custom git completions
  if [[ ! -f "$HOME/.oh-my-zsh/custom/completions/_git" ]]; then
    print-msg "==> updating git completions\n"
    curl -fLo "$HOME/.oh-my-zsh/custom/completions/_git" \
    --create-dirs \
    "https://raw.githubusercontent.com/git/git/v$(git --version | cut -d' ' -f3)/contrib/completion/git-completion.zsh"
  fi
)

update-zsh
